services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db_springboot
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ForSpring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d ForSpring" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my_network
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_java_app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ForSpring
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my_network
volumes:
  postgres_data:
  postgres_backups:

networks:
  my_network:
    driver: bridge
