spring:
  application:
    name: my_practice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://postgres:5432/ForSpring
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          lob:
            non_contextual_creation: true  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false